Add support for sending with WinDivert
chmorgan/sharppcap pull request #142
Opened 2020-06-21 19:26 UTC by kayoub5

Allow sending Packets using WinDivert

# Open Points
### Sub-Interface
@basil00 Could you provide an example/reference how one may be able to find the value of sub-interface ?
All the examples I found mention an interface index, but never a sub-interface index.
Example https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getbestinterface

### Inbound Packet
The test I made was only for outbound packets, and I verified packets were actually sent using Wireshark
@Zeelize could you use the code in the PR and see if it works correctly for your use case in #140?

2020-06-22 00:48 UTC, basil00 commented
I am not sure what it is for.  It is included in WinDivert because the underlying kernel-level packet injection functions require it.  There probably is some uncommon use case for it however.

For most applications, the user is reinjecting a modified packet, so they just reuse the same (sub) interface index as the original captured packet.

2020-06-22 07:28 UTC, Zeelize commented
@kayoub5 Sorry, at the moment I cannot try it. I already wrote a wrapper for my problem and I am not able to use the server for testing. 

If I will have the opportunity, I will use the code.

2020-08-25 20:49 UTC, kayoub5 commented
@chmorgan ready for review and merge

2020-09-18 12:23 UTC, chmorgan commented
Fyi there is some user feedback that would suggest a couple of changes to this PR to expose a setting and another to make it easier maybe to get back some internal reference. That is going on in this discussion, https://github.com/chmorgan/sharppcap/issues/156.

Would love to land this support so we can expose WinDivert to SharpPcap users.

2020-09-20 18:27 UTC, kayoub5 commented
@chmorgan @BarbaTunnelCoder
The latest commits should cover the missing use cases in #156

2020-09-20 20:17 UTC, chmorgan commented
@kayoub5 I'm rebuilding the appveyor commit, then I'll review and we can push out 5.4.0 when this lands, I didn't see your updates here until after updating and pushing 5.3.0.

2020-09-20 20:49 UTC, chmorgan requested changes
A handful of api doc comments and a few code pointer comments and this one looks like its in pretty good shape.

I can't think of why I didn't add a GetPacket() helper to RawCapture earlier, or if this is the best method name but I also can't come up with a reason why this isn't an ok addition either.

Appveyor build is running now, not sure why it failed before.

If you do end up making some changes here can you rebase against master? That should reduce the number of warnings showing up in the CI builds for this PR.

2020-09-20 20:49 UTC, chmorgan commented on SharpPcap/WinDivert/IpHelper.cs
> +        public static NetworkInterface GetBestInterface(IPAddress destinationAddress)
api docs on what this function is intended to do?

2020-09-20 20:49 UTC, chmorgan commented on SharpPcap/WinDivert/IpHelper.cs
> +            var route = new byte[103];
why 103?

2020-09-20 20:49 UTC, chmorgan commented on SharpPcap/WinDivert/WinDivertDevice.cs
> +                src = new IPAddress(p.Slice(12, 4).ToArray());
can we point to where the 12, 16, 8, 24 numbers come from in case someone is looking later?

2020-09-20 20:49 UTC, chmorgan commented on SharpPcap/RawCapture.cs
> +        public virtual Packet GetPacket()
thoughts on api docs for this method?

2020-09-21 19:39 UTC, kayoub5 commented
@chmorgan All requested changes done

2020-09-22 00:29 UTC, chmorgan approved these changes

2020-09-22 00:32 UTC, merged

2020-09-22 00:34 UTC, chmorgan commented
@kayoub5 thank you for this PR!