Add LibpcapVersionAttribute
chmorgan/sharppcap pull request #233
Opened 2021-02-04 08:19 UTC by kayoub5

Usage
```
        [Test]
        [LibpcapVersion(">2.0.0")]
        public void LibpcapVersionAttributeTest()
        {
            // Test will only run if libpcap version > 2.0.0
            Assert.Fail("Libpcap coming from the future");
        }
```
See https://docs.npmjs.com/cli/v6/using-npm/semver for examples on ranges

2021-02-06 11:26 UTC, kayoub5 commented
@chmorgan waiting for your review

2021-02-07 02:22 UTC, chmorgan requested changes
How did you figure it out? It seems pretty obscure.

Are there any tests where we could put this into place via another commit before merging it? As policy we should make use of code we add to see how it looks/works.

2021-02-07 02:51 UTC, kayoub5 commented
@chmorgan Tests updated

2021-02-08 02:22 UTC, chmorgan approved these changes

2021-02-08 06:58 UTC, merged