Statistics Device
chmorgan/sharppcap pull request #234
Opened 2021-02-05 07:30 UTC by kayoub5

2021-02-06 11:25 UTC, kayoub5 commented
@chmorgan waiting for your review

2021-02-08 02:12 UTC, chmorgan requested changes
Added one comment, the other thing I noticed was that code coverage went down a little bit with the change.

2021-02-08 16:46 UTC, kayoub5 commented on Test/RemotePcapTests.cs
> -                    foreach (var device in devices)
`NpcapDevice` is no more, so we only have `LibPcapLiveDevice` left, thus the need for a foreach loop is no more.

2021-02-08 16:48 UTC, kayoub5 commented
@chmorgan Coverage went down, since I removed the Npcap code, and the statistic code I put have fewer lines.
Check codecov report, to double check if I missed a method that should be covered.

2021-02-09 02:13 UTC, chmorgan commented
@kayoub5 yeah it looks like the coverage is good. Its an interesting thing to indicate a negative value when we are taking out code...

2021-02-09 02:17 UTC, chmorgan approved these changes

2021-02-09 07:36 UTC, merged