Auto detect string encoding used by Libpcap
chmorgan/sharppcap pull request #303
Opened 2021-08-31 13:11 UTC by kayoub5

Fixes #300

2021-08-31 15:56 UTC, kayoub5 commented
@chmorgan failed test have nothing to do with strings, could you force re-run it?

2021-08-31 23:27 UTC, chmorgan commented
Wow, this is way way more extensive than I would have thought.

2021-08-31 23:29 UTC, chmorgan requested changes
Reviewed and it looks good to me. Can you update the copyrights on the new file(s) you added with your info? You might also fixup the first commit with the last commit since it looks like the last commit basically fixes the first commit?

2021-08-31 23:47 UTC, kayoub5 commented on Test/Statistics/StatisticsDeviceTest.cs
> +            Thread.Sleep(100);
This change was put in its own commit since it had no relation with actual PR content, but was needed for CI to pass

2021-09-01 00:03 UTC, chmorgan approved these changes

2021-09-01 16:25 UTC, merged